### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by thejsa** [RiiConnect24/Recommended-Sites-US#1]
We could do with a README with more than just the project name.

**Comment by divayprakash** [comment]
@thejsa I'd like to work on this. Could you elaborate the exact requirements?

**Comment by yashbmewada** [comment]
Can you provide the brief description about the project?

**Comment by thejsa** [comment]
@yashbmewada https://riiconnect24.net/ but apparently @larsenv has already done it :3 
Thanks for offering (:

**Comment by spotlightishere** [comment]
Hi!

On the Wii, the Internet Channel allows a recommended list of sites to be loaded. Our service @RiiConnect24 allows that all to be brought back.

This is a script to have different recommended sites per regions.

**Comment by spotlightishere** [comment]
~~I like how it just casually showed up as closed as soon as I commented that~~
